import { useMission } from '../../contexts/MissionContext'
import { useMemo, useState } from "react"
import { AlertCircle, RefreshCcw, LayoutTemplate, Activity, AlertTriangle, Layers, ArrowUpToLine, ArrowDownToLine } from 'lucide-react'
import { Phase3Service } from '@/services/api/phase3Service'
import { useApi } from '@/hooks/useApi'
import { calcMean, calcMax, calcMin } from '@/utils/statistics'
import { calculateCenter, calculateBounds } from '@/utils/geometry'
import { getHealthColor } from '@/components/maps/MarkerFactory'
import { Button } from '@/components/ui/button'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { DataTable } from '@/components/common/DataTable'
import { MetricGrid } from '@/components/common/MetricGrid'
import { SummaryCard } from '@/components/common/SummaryCard'
import { StatisticsCard } from '@/components/common/StatisticsCard'
import { FilterBar } from '@/components/common/FilterBar'
import { BaseMap } from '@/components/maps/BaseMap'
import { ZoneLegend } from '@/components/maps/ZoneLegend'
import { CircleMarker, Popup } from 'react-leaflet'
import { Input } from '@/components/ui/input'

export default function Phase3() {
  const { currentMission } = useMission()
  const { data, loading, error, refetch } = useApi(() => Phase3Service.getData(currentMission), [currentMission])
  const [filterSeverity, setFilterSeverity] = useState<string>('')
  const [minArea, setMinArea] = useState<string>('')
  const [maxArea, setMaxArea] = useState<string>('')

  const metrics = useMemo(() => {
    return {
      total: data.length,
      avgNdvi: calcMean(data, 'avg_ndvi') || calcMean(data, 'ndvi'),
      largestZone: calcMax(data, 'area'),
      smallestZone: calcMin(data, 'area'),
      avgArea: calcMean(data, 'area'),
      highSev: data.filter(d => d.severity?.toLowerCase().includes('high') || d.severity?.toLowerCase().includes('severe')).length,
      modSev: data.filter(d => d.severity?.toLowerCase().includes('moderate')).length,
      avgGridCount: calcMean(data, 'grid_count'),
      maxNdvi: calcMax(data, 'avg_ndvi') || calcMax(data, 'ndvi'),
      minNdvi: calcMin(data, 'avg_ndvi') || calcMin(data, 'ndvi')
    }
  }, [data])

  const mapData = useMemo(() => {
    // Normalizing coord fields in case they change
    const normalizedData = data.map(d => ({...d, lat: d.center_lat ?? d.lat, lon: d.center_lon ?? d.lon}))
    const centerObj = calculateCenter(normalizedData, 'lat', 'lon')
    const bounds = calculateBounds(centerObj.validPoints, 'lat', 'lon')
    return { center: [centerObj.lat, centerObj.lon] as [number, number], bounds, validPoints: centerObj.validPoints }
  }, [data])

  const displayData = useMemo(() => {
    return data.filter(d => {
      const passesMin = minArea ? (d.area || 0) >= parseFloat(minArea) : true
      const passesMax = maxArea ? (d.area || 0) <= parseFloat(maxArea) : true
      return passesMin && passesMax
    })
  }, [data, minArea, maxArea])

  const uniqueSeverity = useMemo(() => Array.from(new Set(data.map(d => d.severity).filter(Boolean))), [data])

  const columns = [
    { key: 'zone_id', label: 'Zone ID', sortable: true },
    { key: 'grid_count', label: 'Grid Count', sortable: true },
    { key: ('avg_ndvi' in (data[0] || {})) ? 'avg_ndvi' : 'ndvi', label: 'Average NDVI', sortable: true },
    { key: 'severity', label: 'Severity', sortable: true },
    { key: 'area', label: 'Area', sortable: true },
    { key: ('center_lat' in (data[0] || {})) ? 'center_lat' : 'lat', label: 'Center Latitude', sortable: true },
    { key: ('center_lon' in (data[0] || {})) ? 'center_lon' : 'lon', label: 'Center Longitude', sortable: true }
  ]

  if (loading) return <div className="animate-pulse h-[800px] bg-slate-100 rounded-lg" />
  if (error) return (
    <div className="flex flex-col items-center justify-center py-16">
      <AlertCircle className="h-12 w-12 text-red-500 mb-4" />
      <p className="text-slate-500">{error}</p>
      <Button onClick={refetch} className="mt-4"><RefreshCcw className="mr-2 h-4 w-4" /> Retry</Button>
    </div>
  )

  return (
    <div className="space-y-6 pb-10">
      <header>
        <h2 className="text-3xl font-bold tracking-tight">Phase 3  Stress Zone Detection</h2>
        <p className="text-slate-500 mt-1">Visualization of clustered crop stress zones generated by the DBSCAN algorithm.</p>
      </header>

      <MetricGrid>
        <SummaryCard title="Total Stress Zones" value={metrics.total} icon={<Layers className="h-4 w-4"/>} />
        <SummaryCard title="Avg NDVI" value={metrics.avgNdvi.toFixed(3)} icon={<Activity className="h-4 w-4"/>} />
        <SummaryCard title="Largest Zone Area" value={metrics.largestZone.toFixed(0)} icon={<LayoutTemplate className="h-4 w-4"/>} />
        <SummaryCard title="Avg Zone Area" value={metrics.avgArea.toFixed(0)} icon={<LayoutTemplate className="h-4 w-4"/>} />
        <SummaryCard title="High Severity" value={metrics.highSev} valueClassName="text-red-600" icon={<AlertTriangle className="h-4 w-4 text-red-500"/>} />
        <SummaryCard title="Moderate Severity" value={metrics.modSev} valueClassName="text-amber-600" icon={<AlertTriangle className="h-4 w-4 text-amber-500"/>} />
      </MetricGrid>

      <div className="grid gap-6 md:grid-cols-1 lg:grid-cols-4">
        <div className="lg:col-span-1">
          <StatisticsCard 
            title="Statistics Panel"
            description="Cluster insights"
            items={[
              { label: 'Largest Zone', value: metrics.largestZone.toFixed(2) + ' m²' },
              { label: 'Smallest Zone', value: metrics.smallestZone.toFixed(2) + ' m²' },
              { label: 'Average Area', value: metrics.avgArea.toFixed(2) + ' m²' },
              { label: 'Avg Grid Count', value: metrics.avgGridCount.toFixed(1) },
              { label: 'Maximum NDVI', value: metrics.maxNdvi.toFixed(3), icon: <ArrowUpToLine className="h-4 w-4 text-green-500"/> },
              { label: 'Minimum NDVI', value: metrics.minNdvi.toFixed(3), icon: <ArrowDownToLine className="h-4 w-4 text-red-500"/> }
            ]}
          />
        </div>
        <div className="lg:col-span-3">
          <BaseMap
            title="Stress Zone Clusters"
            description="Spatial distribution of detected agricultural stress."
            center={mapData.center}
            bounds={mapData.bounds}
            isEmpty={mapData.validPoints.length === 0}
            emptyMessage="No valid clustered stress zones to map."
          >
            {mapData.validPoints.filter(p => {
              const passesMin = minArea ? (p.area || 0) >= parseFloat(minArea) : true
              const passesMax = maxArea ? (p.area || 0) <= parseFloat(maxArea) : true
              return passesMin && passesMax
            }).map((zone, idx) => {
              const color = getHealthColor(zone.severity)
              const radius = Math.max(8, Math.sqrt(zone.area || 0) * 2)
              const ndvi = zone.avg_ndvi ?? zone.ndvi
              return (
                <CircleMarker 
                  key={idx}
                  center={[zone.lat, zone.lon]} 
                  radius={radius}
                  pathOptions={{ fillColor: color, color: color, weight: 2, fillOpacity: 0.6 }}
                >
                  <Popup>
                    <div className="text-sm">
                      <strong>Zone ID:</strong> {zone.zone_id}<br/>
                      <strong>Grid Count:</strong> {zone.grid_count}<br/>
                      <strong>Avg NDVI:</strong> {typeof ndvi === 'number' ? ndvi.toFixed(3) : 'N/A'}<br/>
                      <strong>Severity:</strong> {zone.severity}<br/>
                      <strong>Area:</strong> {zone.area?.toFixed(2) ?? 'N/A'} m²<br/>
                    </div>
                  </Popup>
                </CircleMarker>
              )
            })}
            <ZoneLegend />
          </BaseMap>
        </div>
      </div>

      <Card>
        <CardHeader className="flex flex-col sm:flex-row justify-between items-start sm:items-center space-y-4 sm:space-y-0">
          <div>
            <CardTitle>Stress Zone Clusters Table</CardTitle>
            <CardDescription>Detailed metrics for every DBSCAN clustered zone.</CardDescription>
          </div>
          <div className="flex flex-wrap gap-2 items-center">
            <div className="flex items-center space-x-2 mr-4">
              <span className="text-sm text-slate-500">Area Range:</span>
              <Input type="number" placeholder="Min" className="w-20 h-9" value={minArea} onChange={(e) => setMinArea(e.target.value)} />
              <span className="text-sm text-slate-500">-</span>
              <Input type="number" placeholder="Max" className="w-20 h-9" value={maxArea} onChange={(e) => setMaxArea(e.target.value)} />
            </div>
            <FilterBar value={filterSeverity} options={uniqueSeverity.map(u => ({label: String(u), value: String(u)}))} onChange={setFilterSeverity} defaultLabel="All Severities" />
          </div>
        </CardHeader>
        <CardContent>
          <DataTable 
            data={displayData}
            columns={columns}
            searchKey="zone_id"
            filters={{ severity: filterSeverity }}
          />
        </CardContent>
      </Card>
    </div>
  )
}


